language: python

cache: pip

python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  - XAPIAN='true'
  - XAPIAN='false'

jobs:
  exclude:
    - python: '3.5'
      env: XAPIAN='true'
    - python: '3.6'
      env: XAPIAN='true'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # needed to build Xapian
    - uuid-dev
    - gcc-4.8
    - g++-4.8

install:
  - pip install -r setup/requirements.txt
  - pip install 'sphinx<2'
  - "if [[ $XAPIAN == 'true' ]]; then CXX=g++-4.8 ./setup/install-xapian.sh; fi"
  - "if [[ $XAPIAN == 'true' ]]; then echo 'default_indexer: \'xapian\'' > local_settings.yml; fi"

script:
  - python main.py --test
